## Configuracion de Spring
spring:
  application:
    name: ms-inventory-movies

## Configuracion de Instancia 
server:
  port: 8081

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-movies

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:unir-4640325742.us-east-1.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:7bjt7g0sg6}
    password: ${ELASTICSEARCH_PWD:z1a0tm7zba}
logging:
  level:
    tracer: TRACE
